---
title: "distribution_data.json"
output: html_notebook
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

# Validation run metadata
```{r echo=FALSE}
# add file-specific values here
name <- "distribution_data"
old_synId <-  "syn26274945" 
new_synId <-  "syn27079789"

# not file-specific
old_name <- paste(name, "old", sep="_")
new_name <- paste(name, "new", sep="_")
rules <- paste0("rules_", name)

# print validation summary
cat( name, ".json", "\n", date(),
    "\nold: ", old_synId, " \nnew: ", new_synId,
    sep="")
```

# Downloaded files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, name)
```

# Compared old & new files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
compare(get(old_name), get(new_name), name, summarize=FALSE)
```


# Validated new file against rules
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
source("~/repos/rstudio/agora-data-validation/src/rules/rules_distribution_data.R")
test(get(new_name), get(rules))
```


***
# Validation failure investigations
***


```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(VALIDATION_RULE)
cf <- confront(DATAFRAME, v)
out <- values(cf)
is_unique_fails <- DATAFRAME[!out,]
is_unique_fails
```
