---
title: "manifest validation"
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

# Validation run metadata
```{r echo=FALSE}
# add specific manifest versions here or default to latest
old_synId <-  "syn13363290"   # ALD: syn13363290
new_synId <-  "syn18387112" # ATD: syn18387112


# print validation summary
cat( "manifest.json", "\n", date(),
    "\nold: ", old_synId, " \nnew: ", new_synId,
    sep="")

# json filenames
filenames <- c("ge_reports", "biodomain_info", "data_manifest", "distribution_data", "gene_info", "genes_biodomains", "metabolomics", "network", "neuropath_corr",
                "overall_scores", "proteomics", "protomics_distribution_data", "proteomics_srm", "proteomics_tmt", "rna_distribution_data",
                "rnaseq_differential_expression", "target_exp_validation_harmonized", "team_info")
```

# Download files
## download new and old manifests
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, "manifest", type = 'csv')
```



# Iterate over manifests to download all the referenced files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")

# TODO figure out how to handle alignment when a new file is added to manifest_new
assert(nrow(manifest_old) == nrow(manifest_new))

# create a dataframe from the manifests
versions <- data.frame(filename = filenames, old = paste(manifest_old$id, manifest_old$version, sep = "."), new = paste(manifest_new$id, manifest_new$version, sep = "."))

# remove rows for GE folder and manifest files by index - TODO must be manually updated if the indexes change
versions <- versions[-c(1, 3),]
versions

# download each pair of files
for (i in 1:nrow(versions)) {
  row <- versions[i,]
 download_files(row$old, row$new, row$filename, quiet = FALSE)
}
```


# Compare old & new versions of each file 
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")

cat("\nFiles that have changed:\n")
      
for (i in 1:nrow(versions)) {
  row <- versions[i,]
  old <- get(paste0(row$filename, "_old"))
  new <- get(paste0(row$filename, "_new"))
  identical <- identical(old, new)
  if (!identical) {
      cat("\n", row$filename)
      cat("\n   Number of Records \n   - old: ", nrow(old), "\n   - new: ", nrow(new), "\n   - change: ", nrow(new) - nrow(old), "\n")
      cat("\n    Number of Columns \n   - old :", ncol(old), "\n   - new: ", ncol(new), "\n   - change: ", ncol(new) - ncol(old), "\n")
      
      if (ncol(new) != ncol(old)) {
        old_cols <- colnames(old)
        new_cols <- colnames(new)
    
        cat("\n   Columns dropped: ", setdiff(old_cols,new_cols), sep="\n   - ")
        cat("\n   Columns added: ", setdiff(new_cols,old_cols), sep="\n   - ")
        }
  }
}
```

