---
title: "REPLACEME.json"
output: html_notebook
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

# Validation run metadata
```{r echo=FALSE}
# add file-specific values here
name <- "rna_distribution_data"
old_synId <-  "syn27818985" 
new_synId <-  "syn28094691"  

# not file-specific
old_name <- paste(name, "old", sep="_")
new_name <- paste(name, "new", sep="_")
rules <- paste0("rules_", name)

# print validation summary
cat( name, ".json", "\n", date(),
    "\nold: ", old_synId, " \nnew: ", new_synId,
    sep="")
```

# Downloaded files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, name)
```

# Compared old & new files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
compare(get(old_name), get(new_name), name, summarize=FALSE)
```




# Validated new file against rules
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
source("~/repos/rstudio/agora-data-validation/src/rules/rules_rna_distribution_data.R")
test(get(new_name), get(rules))
```


***
# Validation failure investigations
***


```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(RULE)
cf <- confront(rna_distribution_data_new, v) 
out <- values(cf)
is_unique_fails <- rna_distribution_data_new[!out,]
is_unique_fails
```


***
# Other validation
***
Distribution verification

```{r}

# tissue <- "ACC"
# model <- "AD Diagnosis (males and females)"

tissues <- sort(unique(rna_seq_differential_expression_new$tissue))
models <- unique(rna_seq_differential_expression_new$model)

for (tissue in tissues) {
  
  for (model in models) {

    tissue_rows <- rna_seq_differential_expression_new[rna_seq_differential_expression_new$tissue == tissue,]
    tissue_model_rows <- tissue_rows[tissue_rows$model == model,]
    tissue_model_lfc <- tissue_model_rows$logfc
    
    median <- median(tissue_model_lfc)
    q1 <- quantile(tissue_model_lfc, c(0.25))
    q3 <- quantile(tissue_model_lfc, c(0.75))
    IQR <- q3 - q1
    max <- q3 + (1.5 * IQR)
    min <- q1 - (1.5 * IQR)
    
    
    dist_tissue <- rna_distribution_data_new[rna_distribution_data_new$tissue == tissue,]
    dist_tissue_model <- dist_tissue[dist_tissue$model == model,]
    
    cat("\n\nTissue:", tissue, 
        "\nModel:", model, 
        "\n  Data: ", min, q1, median, q3, max,
        "\n  Distribution: ", dist_tissue_model$min, dist_tissue_model$first_quartile, dist_tissue_model$median, dist_tissue_model$third_quartile, dist_tissue_model$max)
  }}

```



```{r}
tissues <- unique(rna_seq_differential_expression_new$tissue)
models <- unique(rna_seq_differential_expression_new$model)

for (tissue in tissues) {
  for (model in models) {
    tissue_rows <- rna_seq_differential_expression_new[rna_seq_differential_expression_new$tissue == tissue,]
    tissue_model_rows <- rna_seq_differential_expression_new[rna_seq_differential_expression_new$model == model,]
    tissue_model_lfc <- tissue_model_rows$logfc
    median <- median(tissue_model_lfc)
    quartiles <- quantile(tissue_model_lfc, prob=c(.25, .75))
    
    dist_tissue <- rna_distribution_data_new[rna_distribution_data_new$tissue == tissue,]
    dist_tissue_model <- dist_tissue[dist_tissue$model == model,]
    
    cat("\n\nTissue:", tissue, "\nModel:", model, "\n  Calculated Median", median, "\n  File Median", dist_tissue_model$median, "\n   Median diff", median - dist_tissue_model$median, "\n  Calculated Quartiles", quartiles, "\n  File Quartiles", dist_tissue_model$first_quartile, dist_tissue_model$third_quartile)
    
  }
}
```


manually calculate min/max w/1.5IQR 
```{r}
q3 <- rna_distribution_data_new$third_quartile
q1 <- rna_distribution_data_new$first_quartile
IQR <- q3 - q1
EIQR <- IQR * 1.5

mins <- q1 - EIQR
maxs <- q3 + EIQR

rna_distribution_data_new$min <- mins
rna_distribution_data_new$max <- maxs
rna_distribution_data_new
```

Symmetry in distribution data
```{r}

tissues <- unique(rna_seq_differential_expression_new$tissue)
models <- unique(rna_seq_differential_expression_new$model)

for (tissue in tissues) {
  
  for (model in models) {
    
    dist_tissue <- rna_distribution_data_new[rna_distribution_data_new$tissue == tissue,]
    dist_tissue_model <- dist_tissue[dist_tissue$model == model,]
    
    IQR <- dist_tissue_model$third_quartile - dist_tissue_model$first_quartile
    EIQR <- IQR * 1.5
    
    min <- dist_tissue_model$first_quartile - EIQR
    max <- dist_tissue_model$third_quartile + EIQR
    
    cat("\nMin:", min, dist_tissue_model$min, "\nMax:", max, dist_tissue_model$max, "\nIQR:", IQR)

}}
```


```{r}

# tissue <- "ACC"
# model <- "AD Diagnosis (males and females)"

tissues <- sort(unique(rna_seq_differential_expression_new$tissue))
models <- unique(rna_seq_differential_expression_new$model)

for (tissue in tissues) {
  
  for (model in models) {

    tissue_rows <- rna_seq_differential_expression_new[rna_seq_differential_expression_new$tissue == tissue,]
    tissue_model_rows <- tissue_rows[tissue_rows$model == model,]
    tissue_model_lfc <- tissue_model_rows$logfc
    
    median <- median(tissue_model_lfc)
    q1 <- quantile(tissue_model_lfc, c(0.25))
    q3 <- quantile(tissue_model_lfc, c(0.75))
    IQR <- q3 - q1
    max <- q3 + (1.5 * IQR)
    min <- q1 - (1.5 * IQR)
    
    
    dist_tissue <- rna_distribution_data_new[rna_distribution_data_new$tissue == tissue,]
    dist_tissue_model <- dist_tissue[dist_tissue$model == model,]
    
    cat("\n\nTissue:", tissue, 
        "\nModel:", model, 
        "\n  Data: ", min, q1, median, q3, max,
        "\n  Distribution: ", dist_tissue_model$min, dist_tissue_model$first_quartile, dist_tissue_model$median, dist_tissue_model$third_quartile, dist_tissue_model$max)
  }}

```