---
title: "target_exp_validation_harmonized.json"
output: html_notebook
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

# Validation run metadata
```{r echo=FALSE}
# file-specific
name <- "target_exp_validation_harmonized"
old_synId <-  "syn25741027" 
new_synId <-  "syn26868915"

# not file-specific
old_name <- paste(name, "old", sep="_")
new_name <- paste(name, "new", sep="_")
rules <- paste0("rules_", name)

# print validation summary
cat( name, ".json", "\n", date(),
    "\nold: ", old_synId, " \nnew: ", new_synId,
    sep="")
```

# Downloaded files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, name)
```

# Compared old & new files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
compare(get(old_name), get(new_name), name, summarize=FALSE)
```


# Validated new file against rules
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
source("~/repos/rstudio/agora-data-validation/src/rules/rules_target_exp_validation_harmonized.R")
test(get(new_name), get(rules))
```


***
# Validation failure investigations
***

## 	field_length(ensembl_gene_id, n = 15): 1 fail

* This is from the source data
* AG-351

```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(field_length(ensembl_gene_id, n = 15))
cf <- confront(target_exp_validation_harmonized_new, v)
out <- values(cf)
is_unique_fails <- target_exp_validation_harmonized_new[!out,]
is_unique_fails
```

was this issue present in the old data file? => yes
```{r}
target_exp_validation_harmonized_old[target_exp_validation_harmonized_old$ensembl_gene_id == "",]
```


is this from the source data?

```{r}
target_exp_validation_harmonized_source <- download_file("syn24184512", "target_exp_validation_harmonized", type = "csv")
```

=> yes indeed it is! (row 149)

```{r}
target_exp_validation_harmonized_source[target_exp_validation_harmonized_source$Team == "Mayo-UFL-ISB",]
```