---
title: "team_info_test"
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

# Validation run metadata
```{r echo=FALSE}
# file-specific
name <- "team_info"
source_synId <- "syn12615624.15" #csv
old_synId <-  "syn12616884"
new_synId <- "syn17015358"

# not file-specific
old_name <- paste(name, "old", sep="_")
new_name <- paste(name, "new", sep="_")
rules <- paste0("rules_", name)

# print validation summary
cat( name, ".json", "\n", date(),
    "\nold: ", old_synId, " \nnew: ", new_synId,
    sep="")
```

# Downloaded files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, name)
```

```{r}
source <- download_file(source_synId, type = "csv") 
assign(paste(name, "source", sep="_"), source, envir = .GlobalEnv)
```

# Compared old & new files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
compare(get(old_name), get(new_name), name)

cat("\n***team_members***\n")
compare_subobjects(get(old_name), get(new_name), "team", "members")
```


# Validated new file against rules
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
source("~/repos/rstudio/agora-data-validation/src/rules/rules_team_info.R")
test(get(new_name), get(rules))
```

***
# Outstanding validation failures
***
N/A

***
# Validation failure investigations
***


```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(RULE)
cf <- confront(team_info_new, v)
out <- values(cf)
is_unique_fails <- team_info_new[!out,]
is_unique_fails
```

***
# Other validation
***

IU update
```{r}
team_info_old
team_info_new
```

teams
```{r}
unique(team_info_new$team)

```

Reprocessing to pick up new team (AG-667)
```{r}
team_info_new
team_info_old
new_team <- team_info_new[team_info_new$team == "Sage Bionetworks",]
new_team$description
new_team$members
```