---
title: "agora_stats.json"
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

***
Nomination stats
***

## GENE_INFO


## Nomination stats

# EXPECTED based on source files
```{r}
# new_prod = ALD current RC source, old_prod = ALD last released source
# use pinned source files used to generate old_prod and new_prod json
target_list_source_old_prod <- download_file("syn12540368.41", "target_list_source_old_prod", type="csv") # 3.3.0
target_list_source_new_prod <- download_file("syn12540368.47", "target_list_source_new_prod", type="csv") # dec data release
```

# ACTUALS based on gene_info_old & gene_info_new
```{r}
old_synId <-  "syn12548902" 
new_synId <- "syn17015359.61" 

sorted_old <- subset(gene_info_old %>% arrange(TRUE), select = c(ensembl_gene_id, target_nominations))
sorted_new <- subset(gene_info_new %>% arrange(TRUE), select = c(ensembl_gene_id, target_nominations))
 
old <- sorted_old[!is.na(replace_null(sorted_old)$target_nominations),]
new <- sorted_new[!is.na(replace_null(sorted_new)$target_nominations),]
```

# EXPECTED VS ACTUAL
```{r}
#OLD
# total # expected nominations (old source)
expected_noms_old <- length(target_list_source_old$hgnc_symbol)
cat("\ntotal # expected nominations (old source): ", expected_noms_old)

# total # expected nominated targets (old source)
expected_targets_old <- length(unique(target_list_source_old$ensembl_gene_id))
cat("\ntotal # expected nominated targets (old source): ", expected_targets_old)

#total actual nominations (old json)
flat_noms_old <- tidyr::unnest(old, target_nominations)
old_noms <- nrow(flat_noms_old)
cat("\ntotal actual nominations (old json): ", old_noms)

# total actual nominated targets (old json)
old_targets <- length(unique(old$ensembl_gene_id))
cat("\ntotal actual nominated targets (old json): ", old_targets)

# total actual # genes (old json)
old_genes <- length(unique(gene_info_old$ensembl_gene_id))
cat("\ntotal actual # genes (old json): ", old_genes, "\ntotal and unique equal: ", length(gene_info_old$ensembl_gene_id) == length(unique(gene_info_old$ensembl_gene_id)))


# total # expected nominations (new source)
expected_noms_new <- length(target_list_source_new$hgnc_symbol)
cat("\ntotal # expected nominations (new source): ", expected_noms_new)

# total # expected nominated targets (new source)
expected_targets_new <- length(unique(target_list_source_new$ensembl_gene_id))
cat("\ntotal # expected nominated targets (new source): ", expected_targets_new)

# NEW

#total actual nominations (old json)
flat_noms_new <- tidyr::unnest(new, target_nominations,names_sep=".")
new_noms <- nrow(flat_noms_new)
cat("\ntotal actual nominations (new json): ", new_noms)

# total actual nominated targets (old json)
new_targets <- length(unique(new$ensembl_gene_id))
cat("\ntotal actual nominated targets (new json): ", new_targets)

# total actual # genes (new json)
new_genes <- length(unique(gene_info_new$ensembl_gene_id))
cat("\ntotal actual # genes (new json): ", new_genes, "\ntotal and unique equal: ", length(gene_info_new$ensembl_gene_id) == length(unique(gene_info_new$ensembl_gene_id)))
```

```{r}
flat_noms_new
amp <- nrow(flat_noms_new[flat_noms_new$target_nominations.source == "AMP-AD",])
treat <- nrow(flat_noms_new[flat_noms_new$target_nominations.source == "TREAT-AD",])
cc <- nrow(flat_noms_new[flat_noms_new$target_nominations.source == "Community",])
resil <- nrow(flat_noms_new[flat_noms_new$target_nominations.source == "Resilience-AD",])

multiple_nom_targets <- flat_noms_new %>% group_by(ensembl_gene_id) %>% count()
n_multiple_nom_targets <- multiple_nom_targets[multiple_nom_targets$n > 1,]


cat("\nAMP-AD: ", amp)
cat("\nTREAT-AD: ", treat)
cat("\nCC: ", cc)
cat("\nResilience-AD: ", resil)
cat("\nMulti-nom: ", nrow(n_multiple_nom_targets))
```

```{r}
unique(target_list_source_new$Source)
unique(target_list_source_new$Team)
```

## Poster stats
```{r}
nominated_targets_new <- get_subobject(gene_info_new, "target_nominations")
unique(nominated_targets_new$source)

amp_nt <- nominated_targets_new[nominated_targets_new$source == 'AMP-AD',]
treat_nt <- nominated_targets_new[nominated_targets_new$source == 'TREAT-AD',]
com_nt <- nominated_targets_new[nominated_targets_new$source == 'Community',]
res_nt <- nominated_targets_new[nominated_targets_new$source == 'Resilience-AD',]

cat("num amp-ad noms: ", nrow(amp_nt))
cat("num treat-ad noms: ", nrow(treat_nt))
cat("num cc noms: ", nrow(com_nt))
cat("num resilience-ad noms: ", nrow(res_nt))

print(amp_nt)
print(treat_nt)
print(com_nt)
print(res_nt)
```


## ADKP jan newsletter
```{r}
noms_23 <- target_list_source_new_prod[target_list_source_new_prod$initial_nomination == '2023',]
cat("\ntotal '23 noms: ", nrow(noms_23))
cat("\ntotal noms: ", nrow(target_list_source_new_prod))
cat("\ntargets: ", length(unique(target_list_source_new_prod$hgnc_symbol)))

unique(noms_23$Source)

```

## NUM GENES w/EVIDENCE

```{r}

```

find all ENSGs that we have results for (RNA, RNA DE, prot (any), metabl)
```{r}
# rna ME
keeps <- c("ensembl_gene_id", "median_expression")
infos <- subset(gene_info_new, select = keeps)
me <- infos[infos$median_expression != 'NULL',]
rna <- unique(me$ensembl_gene_id)

rna_de <- unique(rna_seq_differential_expression_new$ensembl_gene_id)
metab <- unique(metabolomics_new$ensembl_gene_id)
prot <- unique(proteomics_new$ensembl_gene_id)
prot_tmt <- unique(proteomics_tmt_new$ensembl_gene_id)
prot_srm <- unique(proteomics_srm_new$ensembl_gene_id)

length(purrr::reduce(list(rna, rna_de, metab, prot, prot_tmt, prot_srm),union))
```