---
title: "srm_data.json"
output: html_notebook
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```

# Validation run metadata
```{r echo=FALSE}
# add file-specific values here
name <- "srm_data"
old_synId <-  "syn25741026" 
new_synId <-  "syn25740977"

# not file-specific
old_name <- paste(name, "old", sep="_")
new_name <- paste(name, "new", sep="_")
rules <- paste0("rules_", name)

# print validation summary
cat( name, ".json", "\n", date(),
    "\nold: ", old_synId, " \nnew: ", new_synId,
    sep="")
```

# Downloaded files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, name)
```

# Compared old & new files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
compare(get(old_name), get(new_name), name, summarize=FALSE)
```


# Validated new file against rules
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
source("~/repos/rstudio/agora-data-validation/src/rules/rules_REPLACEME.R")
test(get(new_name), get(rules))
```


***
# Validation failure investigations
***


```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(VALIDATION_RULE)
cf <- confront(DATAFRAME, v)
out <- values(cf)
is_unique_fails <- DATAFRAME[!out,]
is_unique_fails
```


```{r}
srm <- download_file("syn25454540", type='csv')
```


coverage stats
```{r}
nrow(srm_data_new) # 524
peptide <- srm_data_new$uniprotac
gene <- srm_data_new$hgnc_symbol
srm_uid <- paste(gene, peptide, sep = "|")

srm_uniq <- aggregate(srm_uid, by=list(srm_uid), FUN=length)
```

```{r}
lfq_and_srm <- intersect(lfq_uid, srm_uid)
lfq_not_srm <- setdiff(lfq_uid, srm_uid)
srm_not_lfq <- setdiff(srm_uid, lfq_uid)


length(lfq_and_srm) # 104
length(lfq_not_srm) # 5572
length(srm_not_lfq) # 124
```

```{r}
tmt_and_srm <- intersect(tmt_uid, srm_uid)
tmt_not_srm <- setdiff(tmt_uid, srm_uid)
srm_not_tmt <- setdiff(srm_uid, tmt_uid)


length(tmt_and_srm) # 
length(tmt_not_srm) # 
length(srm_not_tmt) # 
```
